In [1]:
import anndata as ad
import pandas as pd

In [2]:
#Download Sciplex
sci = ad.read_h5ad('/lustre/groups/ml01/workspace/olga.novitskaia/data_updated/sciplex/pseudobulk_processed/sep_rep/srivatsan20_sciplex3_processed.h5ad')

## Phase 1

### Download phase1 data

In [3]:
#Download usual l1000 phase1
l1000_1 = ad.read_h5ad('/lustre/groups/ml01/workspace/olga.novitskaia/data_updated/l1000_phase1/pseudobulk_processed/sep_rep/l1000_phase1_level3_deg_ready_landmark_processed.h5ad')

In [4]:
#Download level5 l1000 phase1
l1000_lvl5_1 = ad.read_h5ad('/lustre/groups/ml01/workspace/olga.novitskaia/data_updated/l1000_phase1/level5/level5_phase1_not_filtered.h5ad')

/ictstr01/home/icb/olga.novitskaia/deg_venv/lib/python3.10/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

In [5]:
#Show usual l1000 phase1 cell_type - perturbagen_name - pubchem_cid - pert_type

l1000_1.obs[['cell_type', 'perturbagen_name', 'pubchem_cid', 'pert_type']].drop_duplicates()

,cell_type,perturbagen_name,pubchem_cid,pert_type
sample_id,,,,
ASG001_MCF7_24H_X1_B7_DUO52HI53LO_F13_DMSO_CVCL_0031,CVCL_0031,DMSO,679,compound
ASG001_MCF7_24H_X1_B7_DUO52HI53LO_A06_alpha-estradiol_CVCL_0031,CVCL_0031,alpha-estradiol,450,compound
ASG001_MCF7_24H_X1_B7_DUO52HI53LO_A04_trichostatin-a_CVCL_0031,CVCL_0031,trichostatin-a,6376322,compound
ASG001_MCF7_24H_X1_B7_DUO52HI53LO_A11_trifluoperazine_CVCL_0031,CVCL_0031,trifluoperazine,5566,compound
ASG001_PC3_24H_X2_B7_DUO52HI53LO_E01_DMSO_CVCL_0035,CVCL_0035,DMSO,679,compound
...,...,...,...,...
PCLB002_MCF7_24H_X1_B13_L13_equol_CVCL_0031,CVCL_0031,equol,382975,compound
PCLB002_MCF7_24H_X1_B13_M13_BRD-A08658758_CVCL_0031,CVCL_0031,BRD-A08658758,14459459,compound
PCLB002_MCF7_24H_X1_B13_O01_BRD-K67774729_CVCL_0031,CVCL_0031,BRD-K67774729,54645916,compound
PCLB002_MCF7_24H_X1_B13_O07_BRD-K55533488_CVCL_0031,CVCL_0031,BRD-K55533488,71576758,compound
PCLB002_MCF7_24H_X1_B13_O19_BRD-K19876534_CVCL_0031,CVCL_0031,BRD-K19876534,54646516,compound

In [6]:
#Show level5 l1000 phase1 cell_type - perturbagen_name - pubchem_cid - pert_type

l1000_lvl5_1.obs[['cell_type', 'perturbagen_name', 'pubchem_cid', 'pert_type']].drop_duplicates()

,cell_type,perturbagen_name,pubchem_cid,pert_type
sample_id,,,,
None_None_DMSO_CD34,CD34,DMSO,679,compound
None_None_BRD-A03772856_CD34,CD34,BRD-A03772856,3237298,compound
None_None_trichostatin-a_CD34,CD34,trichostatin-a,6376322,compound
None_None_geldanamycin_CD34,CD34,geldanamycin,13017911,compound
None_None_KUC107191N_CD34,CD34,KUC107191N,51360697,compound
...,...,...,...,...
None_None_KIF11_CVCL_0042,CVCL_0042,KIF11,NaN,genetic
None_None_NDUFAF4_CVCL_0042,CVCL_0042,NDUFAF4,NaN,genetic
None_None_CHMP2A_CVCL_0042,CVCL_0042,CHMP2A,NaN,genetic
None_None_ATG5_CVCL_0042,CVCL_0042,ATG5,NaN,genetic
None_None_SLIRP_CVCL_0042,CVCL_0042,SLIRP,NaN,genetic

### Organize sets of (cell type - pubchem_cid) pairs

In [7]:
# Organizing sets to overlap:

set_sci = set(sci.obs[['cell_type', 'pubchem_cid']].drop_duplicates().itertuples(index=False, name=None))

set_l1000_1 = set(l1000_1.obs[['cell_type', 'pubchem_cid']].drop_duplicates().itertuples(index=False, name=None))

set_l1000_lvl5_1 = set(l1000_lvl5_1.obs[l1000_lvl5_1.obs['pert_type'] == 'compound'][['cell_type', 'pubchem_cid']].drop_duplicates().itertuples(index=False, name=None))

### Overlap

In [8]:
# Overlap Sciplex - l1000 phase1

len(set_sci.intersection(set_l1000_1))

179

In [9]:
# Overlap Sciplex - lvl5 l1000 phase1

len(set_sci.intersection(set_l1000_lvl5_1))

179

In [10]:
# Overlap  (Sciplex - l1000 phase1) - (Sciplex - lvl5 l1000 phase1)

pd.DataFrame(set_sci.intersection(set_l1000_1).intersection(set_sci.intersection(set_l1000_lvl5_1)), columns=['cell_type', 'pubchem_cid'])

     cell_type  pubchem_cid
0    CVCL_0023     11485656
1    CVCL_0031     24901704
2    CVCL_0031      5328779
3    CVCL_0023     72193870
4    CVCL_0023         2746
..         ...          ...
174  CVCL_0023         4858
175  CVCL_0031      9824562
176  CVCL_0023       644241
177  CVCL_0023     24748204
178  CVCL_0023       208908

[179 rows x 2 columns]

In [11]:
# Overlap  l1000 phase1 - lvl5 l1000 phase1

len(set_l1000_1.intersection(set_l1000_lvl5_1))

115596

In [12]:
# Differences  l1000 phase1 - lvl5 l1000 phase1

set_l1000_1 - set_l1000_lvl5_1

{('CVCL_0063', 123596),
 ('CVCL_0063', 176871),
 ('CVCL_0063', 5311510),
 ('CVCL_0063', 10096043),
 ('CVCL_0063', 10184653),
 ('CVCL_0063', 11626560),
 ('CVCL_0063', 24826799)}

In [13]:
# Differences  lvl5 l1000 phase1 - l1000 phase1

set_l1000_lvl5_1 - set_l1000_1

{('CVCL_0031', 962),
 ('CVCL_0033', 962),
 ('CVCL_0062', 962),
 ('CVCL_0178', 962),
 ('CVCL_0332', 962),
 ('CVCL_0598', 962),
 ('CVCL_U486', nan)}

### Organize sets of (cell type - pubchem_cid - perturbagen_name) triplets

In [14]:
set_l1000_1 = set(l1000_1.obs[['cell_type', 'pubchem_cid', 'perturbagen_name']].drop_duplicates().itertuples(index=False, name=None))

set_l1000_lvl5_1 = set(l1000_lvl5_1.obs[l1000_lvl5_1.obs['pert_type'] == 'compound'][['cell_type', 'pubchem_cid', 'perturbagen_name']].drop_duplicates().itertuples(index=False, name=None))

### Overlap

In [15]:
len(set_l1000_1.intersection(set_l1000_lvl5_1))

116588

In [16]:
set_l1000_1 - set_l1000_lvl5_1

{('CVCL_0031', nan, '1B Parent'),
 ('CVCL_0031', nan, 'HDACi1,2 + 3_mix'),
 ('CVCL_0035', nan, '1B Parent'),
 ('CVCL_0035', nan, 'HDACi1,2 + 3_mix'),
 ('CVCL_0063', 123596, 'imatinib'),
 ('CVCL_0063', 176871, 'erlotinib'),
 ('CVCL_0063', 5311510, 'GNF2'),
 ('CVCL_0063', 10096043, 'NVP-AUY922'),
 ('CVCL_0063', 10184653, 'afatinib'),
 ('CVCL_0063', 11626560, 'crizotinib'),
 ('CVCL_0063', 24826799, 'ponatinib'),
 ('CVCL_0132', nan, '1B Parent'),
 ('CVCL_VU89', nan, 'HDACi1,2 + 3_mix')}

In [17]:
set_l1000_lvl5_1 - set_l1000_1

{('CVCL_0023', nan, 'PBS'),
 ('CVCL_0027', nan, 'PBS'),
 ('CVCL_0031', 962, 'H2O'),
 ('CVCL_0031', nan, '1B-parent'),
 ('CVCL_0031', nan, 'HDACi1,2+3_mix'),
 ('CVCL_0031', nan, 'PBS'),
 ('CVCL_0033', 962, 'H2O'),
 ('CVCL_0035', nan, '1B-parent'),
 ('CVCL_0035', nan, 'HDACi1,2+3_mix'),
 ('CVCL_0035', nan, 'PBS'),
 ('CVCL_0062', 962, 'H2O'),
 ('CVCL_0132', nan, '1B-parent'),
 ('CVCL_0132', nan, 'PBS'),
 ('CVCL_0178', 962, 'H2O'),
 ('CVCL_0320', nan, 'PBS'),
 ('CVCL_0332', 962, 'H2O'),
 ('CVCL_0598', 962, 'H2O'),
 ('CVCL_2235', nan, 'PBS'),
 ('CVCL_5136', nan, 'PBS'),
 ('CVCL_U486', nan, 'tunicamycin'),
 ('CVCL_VU89', nan, 'HDACi1,2+3_mix'),
 ('CVCL_VU89', nan, 'PBS')}

### Phase 2

### Download phase2 data

In [18]:
l1000_2 = ad.read_h5ad('/lustre/groups/ml01/workspace/olga.novitskaia/data_updated/l1000_phase2/pseudobulk_processed/sep_rep/l1000_phase2_level3_deg_ready_landmark_processed.h5ad')

In [19]:
l1000_lvl5_2 = ad.read_h5ad('/lustre/groups/ml01/workspace/olga.novitskaia/data_updated/l1000_phase2/level5/level5_phase2_not_filtered.h5ad')

/ictstr01/home/icb/olga.novitskaia/deg_venv/lib/python3.10/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

In [20]:
l1000_2.obs[['cell_type', 'perturbagen_name', 'pubchem_cid', 'pert_type']].drop_duplicates()

,cell_type,perturbagen_name,pubchem_cid,pert_type
sample_id,,,,
LJP005_A375_24H_X1_B19_A03_DMSO_CVCL_0132,CVCL_0132,DMSO,679,compound
LJP005_A375_24H_X1_B19_A12_CP-724714_CVCL_0132,CVCL_0132,CP-724714,9874913,compound
LJP005_A375_24H_X1_B19_E09_PF-431396_CVCL_0132,CVCL_0132,PF-431396,11598628,compound
LJP005_A375_24H_X3_B19_K19_GDC-0980_CVCL_0132,CVCL_0132,GDC-0980,66694608,compound
LJP005_A375_24H_X3_B19_L01_TG-101348_CVCL_0132,CVCL_0132,TG-101348,16722836,compound
...,...,...,...,...
REP.A028_YAPC_24H_X1_B25_O19_piperidolate_CVCL_1794,CVCL_1794,piperidolate,4839,compound
REP.A028_YAPC_24H_X1_B25_P01_quercetin_CVCL_1794,CVCL_1794,quercetin,16212154,compound
REP.A028_YAPC_24H_X1_B25_P07_rosiglitazone_CVCL_1794,CVCL_1794,rosiglitazone,77999,compound
REP.A028_YAPC_24H_X1_B25_P13_gestrinone_CVCL_1794,CVCL_1794,gestrinone,27812,compound
REP.A028_YAPC_24H_X1_B25_P19_cyanocobalamin_CVCL_1794,CVCL_1794,cyanocobalamin,168317484,compound

In [21]:
l1000_lvl5_2.obs[['cell_type', 'perturbagen_name', 'pubchem_cid', 'pert_type']].drop_duplicates()

,cell_type,perturbagen_name,pubchem_cid,pert_type
sample_id,,,,
None_None_DMSO_CVCL_0132,CVCL_0132,DMSO,679,compound
None_None_CP-724714_CVCL_0132,CVCL_0132,CP-724714,9874913,compound
None_None_neratinib_CVCL_0132,CVCL_0132,neratinib,9915743,compound
None_None_crizotinib_CVCL_0132,CVCL_0132,crizotinib,11626560,compound
None_None_HG-5-113-01_CVCL_0132,CVCL_0132,HG-5-113-01,25226483,compound
...,...,...,...,...
None_None_NF1_YAPC.311,YAPC.311,NF1,NaN,genetic
None_None_JUN_YAPC.311,YAPC.311,JUN,NaN,genetic
None_None_FASN_YAPC.311,YAPC.311,FASN,NaN,genetic
None_None_INSM2_YAPC.311,YAPC.311,INSM2,NaN,genetic
None_None_HDAC2_YAPC.311,YAPC.311,HDAC2,NaN,genetic

### Organize sets of (cell type - pubchem_cid) pairs

In [22]:
# Organizing sets to overlap:

set_sci = set(sci.obs[['cell_type', 'pubchem_cid']].drop_duplicates().itertuples(index=False, name=None))

set_l1000_2 = set(l1000_2.obs[['cell_type', 'pubchem_cid']].drop_duplicates().itertuples(index=False, name=None))

set_l1000_lvl5_2 = set(l1000_lvl5_2.obs[l1000_lvl5_2.obs['pert_type'] == 'compound'][['cell_type', 'pubchem_cid']].drop_duplicates().itertuples(index=False, name=None))

In [23]:
len(set_sci.intersection(set_l1000_2))

130

In [24]:
len(set_sci.intersection(set_l1000_lvl5_2))

130

In [25]:
# Overlap  (Sciplex - l1000 phase2) - (Sciplex - lvl5 l1000 phase2)

pd.DataFrame(set_sci.intersection(set_l1000_2).intersection(set_sci.intersection(set_l1000_lvl5_2)), columns=['cell_type', 'pubchem_cid'])

     cell_type  pubchem_cid
0    CVCL_0023     11485656
1    CVCL_0031        66414
2    CVCL_0031     24901704
3    CVCL_0023         2746
4    CVCL_0031      9907093
..         ...          ...
125  CVCL_0023     11167602
126  CVCL_0031         1401
127  CVCL_0031      9824562
128  CVCL_0023       644241
129  CVCL_0023       208908

[130 rows x 2 columns]

In [26]:
len(set_l1000_2.intersection(set_l1000_lvl5_2))

15636

In [27]:
set_l1000_2 - set_l1000_lvl5_2

set()

In [28]:
set_l1000_lvl5_2 - set_l1000_2

set()

### Organize sets of (cell type - pubchem_cid - perturbagen_name) triplets

In [29]:
set_l1000_2 = set(l1000_2.obs[['cell_type', 'pubchem_cid', 'perturbagen_name']].drop_duplicates().itertuples(index=False, name=None))

set_l1000_lvl5_2 = set(l1000_lvl5_2.obs[l1000_lvl5_2.obs['pert_type'] == 'compound'][['cell_type', 'pubchem_cid', 'perturbagen_name']].drop_duplicates().itertuples(index=False, name=None))

### Overlap

In [30]:
len(set_l1000_2.intersection(set_l1000_lvl5_2))

15636

In [31]:
set_l1000_2 - set_l1000_lvl5_2

set()

In [32]:
set_l1000_lvl5_2 - set_l1000_2

set()