In [1]:
print(1)

1

In [2]:
import lamindb as ln

In [3]:
ln.connect("laminlabs/pertdata")

→ the database (1.12.1) is ahead of your installed lamindb package (1.10.0)
→ consider updating lamindb: pip install lamindb>=1.12
→ connected lamindb: laminlabs/pertdata

In [4]:
adata_phase2 = ln.Artifact.get(key='lincs/phase2/Level2_GEX_all_n537590x978.h5ad').load()
adata_phase1_eps = ln.Artifact.get(key='lincs/phase1/Level2_GEX_epsilon_n1269922x978.h5ad').load()
adata_phase1_delta = ln.Artifact.get(key='lincs/phase1/Level2_GEX_delta_n49216x978.h5ad').load()

In [5]:
sci_obs = ln.Artifact.get(key='scperturb/obs/srivatsan20_sciplex3.parquet').load()

In [6]:
sci_var = ln.Artifact.get(key='scperturb/var/srivatsan20_sciplex3.parquet').load()

## .obs
### L1000

In [7]:
adata_phase2.obs

,cell_id,det_plate,det_well,pert_mfc_id,pert_dose,pert_dose_unit,pert_id,pert_iname,pert_type,pert_time,pert_time_unit,source_file,cell_line,pert_compound,pert_genetic,pert_biologic
0,A375,LJP005_A375_24H_X1_B19,A03,dmso,NaN,NaN,DMSO,DMSO,ctl_vehicle,24.0,h,GSE70138_Broad_LINCS_Level2_GEX_n78980x978_201...,A-375,DMSO,NaN,NaN
1,A375,LJP005_A375_24H_X1_B19,A04,dmso,NaN,NaN,DMSO,DMSO,ctl_vehicle,24.0,h,GSE70138_Broad_LINCS_Level2_GEX_n78980x978_201...,A-375,DMSO,NaN,NaN
2,A375,LJP005_A375_24H_X1_B19,A05,dmso,NaN,NaN,DMSO,DMSO,ctl_vehicle,24.0,h,GSE70138_Broad_LINCS_Level2_GEX_n78980x978_201...,A-375,DMSO,NaN,NaN
3,A375,LJP005_A375_24H_X1_B19,A06,dmso,NaN,NaN,DMSO,DMSO,ctl_vehicle,24.0,h,GSE70138_Broad_LINCS_Level2_GEX_n78980x978_201...,A-375,DMSO,NaN,NaN
4,A375,LJP005_A375_24H_X1_B19,A07,BRD-K76908866-001-06-8,10.0,um,BRD-K76908866,CP-724714,trt_cp,24.0,h,GSE70138_Broad_LINCS_Level2_GEX_n78980x978_201...,A-375,CP-724714,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537585,YAPC.311,XPR002_YAPC.311_96H_X3_B22,P20,BRDN0000585533,2.0,uL,BRDN0000585533,LUCIFERASE,ctl_vector,96.0,h,GSE70138_Broad_LINCS_Level2_GEX_n345976x978_20...,YAPC.311,NaN,LUCIFERASE,NaN
537586,YAPC.311,XPR002_YAPC.311_96H_X3_B22,P21,BRDN0000990361,2.0,uL,BRDN0000990361,CDH1,trt_xpr,96.0,h,GSE70138_Broad_LINCS_Level2_GEX_n345976x978_20...,YAPC.311,NaN,NaN,NaN
537587,YAPC.311,XPR002_YAPC.311_96H_X3_B22,P22,BRDN0000735497,2.0,uL,BRDN0000735497,FASN,trt_xpr,96.0,h,GSE70138_Broad_LINCS_Level2_GEX_n345976x978_20...,YAPC.311,NaN,NaN,NaN
537588,YAPC.311,XPR002_YAPC.311_96H_X3_B22,P23,BRDN0000733798,2.0,uL,BRDN0000733798,BCL2L1,trt_xpr,96.0,h,GSE70138_Broad_LINCS_Level2_GEX_n345976x978_20...,YAPC.311,NaN,NaN,NaN
537589,YAPC.311,XPR002_YAPC.311_96H_X3_B22,P24,BRDN0000735629,2.0,uL,BRDN0000735629,TGFBR2,trt_xpr,96.0,h,GSE70138_Broad_LINCS_Level2_GEX_n345976x978_20...,YAPC.311,NaN,NaN,NaN

In [8]:
adata_phase1_eps.obs

,rna_plate,rna_well,pert_id,pert_iname,pert_type,pert_dose,pert_dose_unit,pert_time,pert_time_unit,cell_id,cell_line,pert_compound,pert_genetic,pert_biologic
0,AML001_CD34_24H_X1,A03,BRD-K49071277,securinine,trt_cp,10.00000,um,24,h,CD34,CD34,Securinine,NaN,NaN
1,AML001_CD34_24H_X1,A04,BRD-K49071277,securinine,trt_cp,3.33333,um,24,h,CD34,CD34,Securinine,NaN,NaN
2,AML001_CD34_24H_X1,A05,DMSO,DMSO,ctl_vehicle,0.10000,%,24,h,CD34,CD34,DMSO,NaN,NaN
3,AML001_CD34_24H_X1,A07,BRD-K47084999,BRD-K47084999,trt_cp,10.00000,um,24,h,CD34,CD34,BRD-K47084999,NaN,NaN
4,AML001_CD34_24H_X1,A08,BRD-K47084999,BRD-K47084999,trt_cp,3.33333,um,24,h,CD34,CD34,BRD-K47084999,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1269917,TAK004_U2OS_96H_X1,P20,TRCN0000040164,RB1,trt_sh,1.00000,ul,96,h,U2OS,U-2 OS cell,NaN,RB1,NaN
1269918,TAK004_U2OS_96H_X1,P21,TRCN0000314735,HDAC4,trt_sh,1.00000,ul,96,h,U2OS,U-2 OS cell,NaN,HDAC4,NaN
1269919,TAK004_U2OS_96H_X1,P22,TRCN0000019471,WWTR1,trt_sh,1.00000,ul,96,h,U2OS,U-2 OS cell,NaN,WWTR1,NaN
1269920,TAK004_U2OS_96H_X1,P23,TRCN0000072210,RFP,ctl_vector,1.00000,ul,96,h,U2OS,U-2 OS cell,NaN,RFP,NaN
1269921,TAK004_U2OS_96H_X1,P24,TRCN0000019469,WWTR1,trt_sh,1.00000,ul,96,h,U2OS,U-2 OS cell,NaN,WWTR1,NaN

In [9]:
adata_phase1_delta.obs

,rna_plate,rna_well,pert_id,pert_iname,pert_type,pert_dose,pert_dose_unit,pert_time,pert_time_unit,cell_id,cell_line,pert_compound,pert_genetic,pert_biologic
0,ERG003_VCAP_24H_X1,A03,CMAP-000,UnTrt,ctl_untrt,-666.0,-666,24,h,VCAP,VCaP cell,NaN,NaN,UnTrt
1,ERG003_VCAP_24H_X1,A04,CMAP-000,UnTrt,ctl_untrt,-666.0,-666,24,h,VCAP,VCaP cell,NaN,NaN,UnTrt
2,ERG003_VCAP_24H_X1,A05,CMAP-ERGK-002,GFP,ctl_vector,25.0,ul,24,h,VCAP,VCaP cell,NaN,GFP,NaN
3,ERG003_VCAP_24H_X1,A06,CMAP-ERGK-002,GFP,ctl_vector,25.0,ul,24,h,VCAP,VCaP cell,NaN,GFP,NaN
4,ERG003_VCAP_24H_X1,A07,CMAP-ERGK-002,GFP,ctl_vector,25.0,ul,24,h,VCAP,VCaP cell,NaN,GFP,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49211,KDA010_PC3_96H_X3,P19,TRCN0000145620,pgw,ctl_vector,-666.0,-666,96,h,PC3,PC-3,NaN,pgw,NaN
49212,KDA010_PC3_96H_X3,P20,TRCN0000145620,pgw,ctl_vector,-666.0,-666,96,h,PC3,PC-3,NaN,pgw,NaN
49213,KDA010_PC3_96H_X3,P21,TRCN0000000000,UnTrt,ctl_untrt,-666.0,-666,96,h,PC3,PC-3,NaN,NaN,NaN
49214,KDA010_PC3_96H_X3,P22,TRCN0000000000,UnTrt,ctl_untrt,-666.0,-666,96,h,PC3,PC-3,NaN,NaN,NaN
49215,KDA010_PC3_96H_X3,P23,TRCN0000000000,UnTrt,ctl_untrt,-666.0,-666,96,h,PC3,PC-3,NaN,NaN,NaN

### Sci-plex

In [10]:
sci_obs

,pert_target,pert_compound,pert_dose,pert_time,organism,cell_line,cell_type,disease,tissue_type,tissue,assay,suspension_type,donor_id,sex,self_reported_ethnicity,development_stage,pert_name,pert_type,ncounts,well,plate,replicate,time,dose_value,pathway_level_1,pathway_level_2,pathway,dose_unit,cancer
A01_E09_RT_BC_100_Lig_BC_147,Aurora,TAK-901,10000.0nM,24h,human,MCF7,mammary gland epithelial cell,breast adenocarcinoma,cell culture,breast,sci-Plex,nucleus,unknown,female,European,unknown,TAK-901,compound,2957,plate6_A9,plate44,rep2,24.0,10000.0,Tyrosine kinase signaling,RTK activity,Cell Cycle,nM,True
A01_E09_RT_BC_100_Lig_BC_186,EGFR,AG-490,10.0nM,24h,human,MCF7,mammary gland epithelial cell,breast adenocarcinoma,cell culture,breast,sci-Plex,nucleus,unknown,female,European,unknown,AG-490 (Tyrphostin B42),compound,1528,plate8_H3,plate46,rep2,24.0,10.0,Tyrosine kinase signaling,RTK activity,Protein Tyrosine Kinase,nM,True
A01_E09_RT_BC_100_Lig_BC_196,HDAC,abexinostat,1000.0nM,24h,human,MCF7,mammary gland epithelial cell,breast adenocarcinoma,cell culture,breast,sci-Plex,nucleus,unknown,female,European,unknown,Abexinostat (PCI-24781),compound,1881,plate3_C2,plate41,rep2,24.0,1000.0,Epigenetic regulation,Histone deacetylation,Cytoskeletal Signaling,nM,True
A01_E09_RT_BC_100_Lig_BC_213,Aurora,alisertib,1000.0nM,72h,human,A549,pneumocyte,lung adenocarcinoma,cell culture,lung,sci-Plex,nucleus,unknown,male,European,unknown,Alisertib (MLN8237),compound,1700,plate9_E3,plate51,rep2,72.0,1000.0,Cell cycle regulation,Aurora kinase activity,Cell Cycle,nM,True
A01_E09_RT_BC_100_Lig_BC_220,DNA,busulfan,10000.0nM,24h,human,K-562,lymphoblast,"chronic myelogenous leukemia, BCR-ABL1 positive",cell culture,bone marrow,sci-Plex,nucleus,unknown,female,European,unknown,Busulfan,compound,1430,plate8_H10,plate30,rep2,24.0,10000.0,DNA damage & DNA repair,Alkylating agent,DNA Damage,nM,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
H12_F10_RT_BC_9_Lig_BC_237,"Src,Sirtuin,PKC,PI3K",quercetin,1000.0nM,24h,human,MCF7,mammary gland epithelial cell,breast adenocarcinoma,cell culture,breast,sci-Plex,nucleus,unknown,female,European,unknown,Quercetin,compound,759,plate5_C2,plate43,rep2,24.0,1000.0,Antioxidant,Antioxidant,Epigenetics,nM,True
H12_F10_RT_BC_9_Lig_BC_274,Androgen,Andarine,10.0nM,24h,human,K-562,lymphoblast,"chronic myelogenous leukemia, BCR-ABL1 positive",cell culture,bone marrow,sci-Plex,nucleus,unknown,female,European,unknown,Andarine,compound,1108,plate8_B9,plate6,rep1,24.0,10.0,Nuclear receptor signaling,Nuclear receptor activity,Endocrinology & Hormones,nM,True
H12_F10_RT_BC_9_Lig_BC_291,PARP,Iniparib,100.0nM,24h,human,MCF7,mammary gland epithelial cell,breast adenocarcinoma,cell culture,breast,sci-Plex,nucleus,unknown,female,European,unknown,Iniparib (BSI-201),compound,714,plate3_B8,plate41,rep2,24.0,100.0,DNA damage & DNA repair,ADP-rybosilation,DNA Damage,nM,True
H12_F10_RT_BC_9_Lig_BC_298,PKC,Bisindolylmaleimide,100.0nM,24h,human,MCF7,mammary gland epithelial cell,breast adenocarcinoma,cell culture,breast,sci-Plex,nucleus,unknown,female,European,unknown,Bisindolylmaleimide IX (Ro 31-8220 Mesylate),compound,1659,plate4_D4,plate18,rep1,24.0,100.0,PKC signaling,PKC activitiy,TGF-beta/Smad,nM,True
H12_F10_RT_BC_9_Lig_BC_4,NaN,NaN,0.0nM,,human,NaN,NaN,NaN,cell culture,NaN,sci-Plex,nucleus,unknown,NaN,NaN,unknown,NaN,compound,726,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,nM,True

## .var
### L1000

In [11]:
adata_phase2.var

,rid,pr_analyte_id,pr_analyte_num,pr_bset_id,pr_lua_id,pr_pool_id,pr_gene_symbol,pr_gene_title,pr_is_bing,pr_is_inf,pr_is_lmark
pr_gene_id,,,,,,,,,,,
5720,200814_at,Analyte 11,11,dp52,LUA-3404,epsilon,PSME1,"proteasome (prosome, macropain) activator subu...",1,1,1
55847,218597_s_at,Analyte 12,12,dp52,LUA-3431,epsilon,CISD1,CDGSH iron sulfur domain 1,1,1,1
7416,217140_s_at,Analyte 12,12,dp53,LUA-4000,epsilon,VDAC1,voltage-dependent anion channel 1,1,1,1
10174,209253_at,Analyte 13,13,dp53,LUA-4040,epsilon,SORBS3,sorbin and SH3 domain containing 3,1,1,1
25803,214404_x_at,Analyte 13,13,dp52,LUA-1326,epsilon,SPDEF,SAM pointed domain containing ets transcriptio...,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
10153,203341_at,Analyte 498,498,dp53,LUA-876,epsilon,CEBPZ,"CCAAT/enhancer binding protein (C/EBP), zeta",1,1,1
5566,202801_at,Analyte 498,498,dp52,LUA-81,epsilon,PRKACA,"protein kinase, cAMP-dependent, catalytic, alpha",1,1,1
2597,217398_x_at,Analyte 499,499,dp53,LUA-576,epsilon,GAPDH,glyceraldehyde-3-phosphate dehydrogenase,1,1,1
874,205379_at,Analyte 500,500,dp53,LUA-4022,epsilon,CBR3,carbonyl reductase 3,1,1,1
57149,203897_at,Analyte 500,500,dp52,LUA-589,epsilon,LYRM1,LYR motif containing 1,1,1,1

In [12]:
adata_phase1_eps.var

,pr_gene_symbol,pr_gene_title,pr_is_lm,pr_is_bing
rid,,,,
780,DDR1,discoidin domain receptor tyrosine kinase 1,1,1
7849,PAX8,paired box 8,1,1
6193,RPS5,ribosomal protein S5,1,1
23,ABCF1,ATP binding cassette subfamily F member 1,1,1
9552,SPAG7,sperm associated antigen 7,1,1
...,...,...,...,...
5467,PPARD,peroxisome proliferator activated receptor delta,1,1
2767,GNA11,guanine nucleotide binding protein (G protein)...,1,1
23038,WDTC1,WD and tetratricopeptide repeats 1,1,1
57048,PLSCR3,phospholipid scramblase 3,1,1
79716,NPEPL1,aminopeptidase-like 1,1,1

In [13]:
adata_phase1_delta.var

       pr_gene_symbol                                      pr_gene_title
rid
780              DDR1        discoidin domain receptor tyrosine kinase 1
7849             PAX8                                       paired box 8
23              ABCF1          ATP binding cassette subfamily F member 1
9552            SPAG7                         sperm associated antigen 7
10921           RNPS1         RNA binding protein S1, serine-rich domain
...               ...                                                ...
2767            GNA11  guanine nucleotide binding protein (G protein)...
23038           WDTC1                 WD and tetratricopeptide repeats 1
57048          PLSCR3                          phospholipid scramblase 3
205564          SENP5                 SUMO1/sentrin specific peptidase 5
79716          NPEPL1                              aminopeptidase-like 1

[978 rows x 2 columns]

### Sci-Plex

In [14]:
sci_var

                      symbol
ensembl_id
ENSG00000000003       TSPAN6
ENSG00000000005         TNMD
ENSG00000000419         DPM1
ENSG00000000457        SCYL3
ENSG00000000460     C1orf112
...                      ...
ENSG00000284744   AL591163.1
ENSG00000284745   AL589702.1
ENSG00000284746  AC068587.10
ENSG00000284747   AL034417.4
ENSG00000284748   AL513220.1

[58302 rows x 1 columns]